version: '3'

services:

  database-provider:
    build: ./database-provider
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: 'mysql:latest'
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: csb_strat_1