version: '3'

services:

  database-provider:
    build: ./database-provider
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: 'postgres:14'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: csb_strat_1